server:
  port: ${spring.boot.server.port:8800}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/jpeg,image/jpg,image/png,image/bmp,image/gif
    min-response-size: 256
  http2:
    enabled: true

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://${eureka.host:localhost}:${server.port:8800}/eureka

logging:
    path: logs/es
